version: '3'
services:
  resit-boilerplate-app-db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      -  /opt/backup:/var/lib/postgresql/data
    
  resit-boilerplate-app-web:
    build: .
    command: /bin/sh init.sh
    ports:
      - "3000:3000"
    depends_on:
      - resit-boilerplate-app-db
  redis:
    image: 'redis'
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '6379:6379'
  sidekiq:
    depends_on:
      - redis
    build: .
    links:
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml -e production
volumes:
  resit-boilerplate-app-db:
