default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres
  username: postgres
  password: 1234
  host: 172.17.0.1
  port: 5437

development:
  <<: *default
  database: resit_boilerplate_dev

test:
  <<: *default
  database: resit_boilerplate_test

production:
  adapter: postgresql
  database: resit_boilerplate_production
  pool: 5
  host: resit_boilerplate_app-db
  username: resit_boilerplate_user
  password: password
