default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: ultramar_ops_dev

test:
  <<: *default
  database: ultramar_ops_test

production:
  adapter: postgresql
  database: ultramar_ops_production
  pool: 5
  host: ultramar-ops-db
  username: ultramar_ops_user
  password: ai6ab76378936be9786876978a6d978s6ds867s86d87as6d876sgd7
